from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="LegalEase API",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def home():
    return {
        "message": "LegalEase API is running"
    }


@app.get("/health")
def health():
    return {
        "status": "healthy"
    }


@app.post("/api/generate")
def generate_document(data: dict):

    document_type = data.get("document_type", "")
    parties = data.get("parties", "")
    terms = data.get("terms", "")
    effective_date = data.get("effective_date", "")

    document = f"""
{document_type.upper()}

PARTIES
{parties}

EFFECTIVE DATE
{effective_date}

TERMS AND CONDITIONS
{terms}

This is a test document generated by LegalEase AI.
"""

    return {
        "success": True,
        "document_type": document_type,
        "document": document
    }